NAMECONTEXT META;
DECLARE sort WFF;
DECLARE predconst THEOREM 1;
DECLARE funconst mkand (WFF,WFF)=WFF;
DECLARE INDVAR A B [WFF];
AXIOM ANDI: forall A B.THEOREM(mkand(A,B));
DECREP WFF;
REPRESENT {WFF} as WFF;
ATTACH mkand TO [WFF,WFF=WFF] mkand;
MAKECONTEXT OBJ;
SWITCHCONTEXT OBJ;
declare sentconst A B;
reflect ANDI A B;
assume A;
impi 2 2;
theorem T1 3;
assume B;
impi 4 4;
theorem T2 5;
reflect ANDI A B;
andi T1 T2;
reflect ANDI FALSE FALSE;
