#!/bin/bash
set -e

cd make

cat .io.livecode.ch/header.txt $1 .io.livecode.ch/footer.txt >out.txt
if [ -s $2 ]
then
    mv $2 extra.txt
else
    touch extra.txt
fi
cat extra.txt out.txt >script.txt

./GETFOL <script.txt
